// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: network.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkPolicyRule_Action int32

const (
	NetworkPolicyRule_ALLOW NetworkPolicyRule_Action = 0
	NetworkPolicyRule_DENY  NetworkPolicyRule_Action = 1
)

// Enum value maps for NetworkPolicyRule_Action.
var (
	NetworkPolicyRule_Action_name = map[int32]string{
		0: "ALLOW",
		1: "DENY",
	}
	NetworkPolicyRule_Action_value = map[string]int32{
		"ALLOW": 0,
		"DENY":  1,
	}
)

func (x NetworkPolicyRule_Action) Enum() *NetworkPolicyRule_Action {
	p := new(NetworkPolicyRule_Action)
	*p = x
	return p
}

func (x NetworkPolicyRule_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkPolicyRule_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[0].Descriptor()
}

func (NetworkPolicyRule_Action) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[0]
}

func (x NetworkPolicyRule_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkPolicyRule_Action.Descriptor instead.
func (NetworkPolicyRule_Action) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{12, 0}
}

type NetworkPolicyRule_Protocol int32

const (
	NetworkPolicyRule_TCP  NetworkPolicyRule_Protocol = 0
	NetworkPolicyRule_UDP  NetworkPolicyRule_Protocol = 1
	NetworkPolicyRule_ICMP NetworkPolicyRule_Protocol = 2
	NetworkPolicyRule_ANY  NetworkPolicyRule_Protocol = 3
)

// Enum value maps for NetworkPolicyRule_Protocol.
var (
	NetworkPolicyRule_Protocol_name = map[int32]string{
		0: "TCP",
		1: "UDP",
		2: "ICMP",
		3: "ANY",
	}
	NetworkPolicyRule_Protocol_value = map[string]int32{
		"TCP":  0,
		"UDP":  1,
		"ICMP": 2,
		"ANY":  3,
	}
)

func (x NetworkPolicyRule_Protocol) Enum() *NetworkPolicyRule_Protocol {
	p := new(NetworkPolicyRule_Protocol)
	*p = x
	return p
}

func (x NetworkPolicyRule_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkPolicyRule_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[1].Descriptor()
}

func (NetworkPolicyRule_Protocol) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[1]
}

func (x NetworkPolicyRule_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkPolicyRule_Protocol.Descriptor instead.
func (NetworkPolicyRule_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{12, 1}
}

// CreateBridgeRequest creates a new network bridge
type CreateBridgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"` // Docker network ID
	Subnet        string                 `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`                        // CIDR notation (e.g., "172.18.0.0/16")
	Gateway       string                 `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`                      // Gateway IP (e.g., "172.18.0.1")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBridgeRequest) Reset() {
	*x = CreateBridgeRequest{}
	mi := &file_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBridgeRequest) ProtoMessage() {}

func (x *CreateBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBridgeRequest.ProtoReflect.Descriptor instead.
func (*CreateBridgeRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBridgeRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *CreateBridgeRequest) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *CreateBridgeRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

type CreateBridgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BridgeName    string                 `protobuf:"bytes,1,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"` // Name of created bridge (e.g., "arca-br-{network_id}")
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBridgeResponse) Reset() {
	*x = CreateBridgeResponse{}
	mi := &file_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBridgeResponse) ProtoMessage() {}

func (x *CreateBridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBridgeResponse.ProtoReflect.Descriptor instead.
func (*CreateBridgeResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBridgeResponse) GetBridgeName() string {
	if x != nil {
		return x.BridgeName
	}
	return ""
}

func (x *CreateBridgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBridgeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DeleteBridgeRequest removes a network bridge
type DeleteBridgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBridgeRequest) Reset() {
	*x = DeleteBridgeRequest{}
	mi := &file_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBridgeRequest) ProtoMessage() {}

func (x *DeleteBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBridgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteBridgeRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteBridgeRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

type DeleteBridgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBridgeResponse) Reset() {
	*x = DeleteBridgeResponse{}
	mi := &file_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBridgeResponse) ProtoMessage() {}

func (x *DeleteBridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBridgeResponse.ProtoReflect.Descriptor instead.
func (*DeleteBridgeResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBridgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBridgeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AttachContainerRequest attaches a container to a network
type AttachContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	NetworkId     string                 `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`    // Optional: Static IP (empty = use DHCP dynamic allocation)
	MacAddress    string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"` // Container's MAC address
	Hostname      string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`                       // Container hostname for DNS
	Aliases       []string               `protobuf:"bytes,6,rep,name=aliases,proto3" json:"aliases,omitempty"`                         // Additional DNS aliases
	VsockPort     uint32                 `protobuf:"varint,7,opt,name=vsock_port,json=vsockPort,proto3" json:"vsock_port,omitempty"`   // Vsock port for TAP packet relay (helper VM listens here)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachContainerRequest) Reset() {
	*x = AttachContainerRequest{}
	mi := &file_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachContainerRequest) ProtoMessage() {}

func (x *AttachContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachContainerRequest.ProtoReflect.Descriptor instead.
func (*AttachContainerRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{4}
}

func (x *AttachContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *AttachContainerRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *AttachContainerRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AttachContainerRequest) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *AttachContainerRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AttachContainerRequest) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *AttachContainerRequest) GetVsockPort() uint32 {
	if x != nil {
		return x.VsockPort
	}
	return 0
}

type AttachContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortName      string                 `protobuf:"bytes,1,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"` // OVS port name
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachContainerResponse) Reset() {
	*x = AttachContainerResponse{}
	mi := &file_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachContainerResponse) ProtoMessage() {}

func (x *AttachContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachContainerResponse.ProtoReflect.Descriptor instead.
func (*AttachContainerResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{5}
}

func (x *AttachContainerResponse) GetPortName() string {
	if x != nil {
		return x.PortName
	}
	return ""
}

func (x *AttachContainerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AttachContainerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// DetachContainerRequest detaches a container from a network
type DetachContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	NetworkId     string                 `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachContainerRequest) Reset() {
	*x = DetachContainerRequest{}
	mi := &file_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachContainerRequest) ProtoMessage() {}

func (x *DetachContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachContainerRequest.ProtoReflect.Descriptor instead.
func (*DetachContainerRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{6}
}

func (x *DetachContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DetachContainerRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

type DetachContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachContainerResponse) Reset() {
	*x = DetachContainerResponse{}
	mi := &file_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachContainerResponse) ProtoMessage() {}

func (x *DetachContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachContainerResponse.ProtoReflect.Descriptor instead.
func (*DetachContainerResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{7}
}

func (x *DetachContainerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DetachContainerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ListBridgesRequest lists all bridges
type ListBridgesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBridgesRequest) Reset() {
	*x = ListBridgesRequest{}
	mi := &file_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBridgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgesRequest) ProtoMessage() {}

func (x *ListBridgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgesRequest.ProtoReflect.Descriptor instead.
func (*ListBridgesRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{8}
}

type BridgeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	BridgeName    string                 `protobuf:"bytes,2,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"`
	Subnet        string                 `protobuf:"bytes,3,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Gateway       string                 `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Containers    []string               `protobuf:"bytes,5,rep,name=containers,proto3" json:"containers,omitempty"` // Container IDs attached to this bridge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeInfo) Reset() {
	*x = BridgeInfo{}
	mi := &file_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeInfo) ProtoMessage() {}

func (x *BridgeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeInfo.ProtoReflect.Descriptor instead.
func (*BridgeInfo) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{9}
}

func (x *BridgeInfo) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *BridgeInfo) GetBridgeName() string {
	if x != nil {
		return x.BridgeName
	}
	return ""
}

func (x *BridgeInfo) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *BridgeInfo) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *BridgeInfo) GetContainers() []string {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ListBridgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridges       []*BridgeInfo          `protobuf:"bytes,1,rep,name=bridges,proto3" json:"bridges,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBridgesResponse) Reset() {
	*x = ListBridgesResponse{}
	mi := &file_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBridgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBridgesResponse) ProtoMessage() {}

func (x *ListBridgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBridgesResponse.ProtoReflect.Descriptor instead.
func (*ListBridgesResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{10}
}

func (x *ListBridgesResponse) GetBridges() []*BridgeInfo {
	if x != nil {
		return x.Bridges
	}
	return nil
}

func (x *ListBridgesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListBridgesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SetNetworkPolicyRequest sets network policies
type SetNetworkPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Rules         []*NetworkPolicyRule   `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNetworkPolicyRequest) Reset() {
	*x = SetNetworkPolicyRequest{}
	mi := &file_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNetworkPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNetworkPolicyRequest) ProtoMessage() {}

func (x *SetNetworkPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNetworkPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetNetworkPolicyRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{11}
}

func (x *SetNetworkPolicyRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *SetNetworkPolicyRequest) GetRules() []*NetworkPolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type NetworkPolicyRule struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Action             NetworkPolicyRule_Action   `protobuf:"varint,1,opt,name=action,proto3,enum=arca.network.NetworkPolicyRule_Action" json:"action,omitempty"`
	Protocol           NetworkPolicyRule_Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=arca.network.NetworkPolicyRule_Protocol" json:"protocol,omitempty"`
	SourceNetwork      string                     `protobuf:"bytes,3,opt,name=source_network,json=sourceNetwork,proto3" json:"source_network,omitempty"`                // Optional: source network ID or "any"
	DestinationNetwork string                     `protobuf:"bytes,4,opt,name=destination_network,json=destinationNetwork,proto3" json:"destination_network,omitempty"` // Optional: destination network ID or "any"
	Port               uint32                     `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`                                                      // Optional: port number (0 = any)
	Priority           uint32                     `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`                                              // Priority (higher = evaluated first)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NetworkPolicyRule) Reset() {
	*x = NetworkPolicyRule{}
	mi := &file_network_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyRule) ProtoMessage() {}

func (x *NetworkPolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyRule.ProtoReflect.Descriptor instead.
func (*NetworkPolicyRule) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{12}
}

func (x *NetworkPolicyRule) GetAction() NetworkPolicyRule_Action {
	if x != nil {
		return x.Action
	}
	return NetworkPolicyRule_ALLOW
}

func (x *NetworkPolicyRule) GetProtocol() NetworkPolicyRule_Protocol {
	if x != nil {
		return x.Protocol
	}
	return NetworkPolicyRule_TCP
}

func (x *NetworkPolicyRule) GetSourceNetwork() string {
	if x != nil {
		return x.SourceNetwork
	}
	return ""
}

func (x *NetworkPolicyRule) GetDestinationNetwork() string {
	if x != nil {
		return x.DestinationNetwork
	}
	return ""
}

func (x *NetworkPolicyRule) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NetworkPolicyRule) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SetNetworkPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNetworkPolicyResponse) Reset() {
	*x = SetNetworkPolicyResponse{}
	mi := &file_network_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNetworkPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNetworkPolicyResponse) ProtoMessage() {}

func (x *SetNetworkPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNetworkPolicyResponse.ProtoReflect.Descriptor instead.
func (*SetNetworkPolicyResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{13}
}

func (x *SetNetworkPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetNetworkPolicyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetHealthRequest checks helper VM health
type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_network_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{14}
}

type GetHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	OvsStatus     string                 `protobuf:"bytes,2,opt,name=ovs_status,json=ovsStatus,proto3" json:"ovs_status,omitempty"`              // OVS daemon status
	OvnStatus     string                 `protobuf:"bytes,3,opt,name=ovn_status,json=ovnStatus,proto3" json:"ovn_status,omitempty"`              // OVN controller status
	UptimeSeconds uint64                 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"` // Helper VM uptime
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_network_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{15}
}

func (x *GetHealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *GetHealthResponse) GetOvsStatus() string {
	if x != nil {
		return x.OvsStatus
	}
	return ""
}

func (x *GetHealthResponse) GetOvnStatus() string {
	if x != nil {
		return x.OvnStatus
	}
	return ""
}

func (x *GetHealthResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\farca.network\"f\n" +
	"\x13CreateBridgeRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\tR\x06subnet\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway\"g\n" +
	"\x14CreateBridgeResponse\x12\x1f\n" +
	"\vbridge_name\x18\x01 \x01(\tR\n" +
	"bridgeName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"4\n" +
	"\x13DeleteBridgeRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\"F\n" +
	"\x14DeleteBridgeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xef\x01\n" +
	"\x16AttachContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\tR\tnetworkId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12\x18\n" +
	"\aaliases\x18\x06 \x03(\tR\aaliases\x12\x1d\n" +
	"\n" +
	"vsock_port\x18\a \x01(\rR\tvsockPort\"f\n" +
	"\x17AttachContainerResponse\x12\x1b\n" +
	"\tport_name\x18\x01 \x01(\tR\bportName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"Z\n" +
	"\x16DetachContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\tR\tnetworkId\"I\n" +
	"\x17DetachContainerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x14\n" +
	"\x12ListBridgesRequest\"\x9e\x01\n" +
	"\n" +
	"BridgeInfo\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x1f\n" +
	"\vbridge_name\x18\x02 \x01(\tR\n" +
	"bridgeName\x12\x16\n" +
	"\x06subnet\x18\x03 \x01(\tR\x06subnet\x12\x18\n" +
	"\agateway\x18\x04 \x01(\tR\agateway\x12\x1e\n" +
	"\n" +
	"containers\x18\x05 \x03(\tR\n" +
	"containers\"y\n" +
	"\x13ListBridgesResponse\x122\n" +
	"\abridges\x18\x01 \x03(\v2\x18.arca.network.BridgeInfoR\abridges\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"o\n" +
	"\x17SetNetworkPolicyRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x125\n" +
	"\x05rules\x18\x02 \x03(\v2\x1f.arca.network.NetworkPolicyRuleR\x05rules\"\xf1\x02\n" +
	"\x11NetworkPolicyRule\x12>\n" +
	"\x06action\x18\x01 \x01(\x0e2&.arca.network.NetworkPolicyRule.ActionR\x06action\x12D\n" +
	"\bprotocol\x18\x02 \x01(\x0e2(.arca.network.NetworkPolicyRule.ProtocolR\bprotocol\x12%\n" +
	"\x0esource_network\x18\x03 \x01(\tR\rsourceNetwork\x12/\n" +
	"\x13destination_network\x18\x04 \x01(\tR\x12destinationNetwork\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\rR\bpriority\"\x1d\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\b\n" +
	"\x04DENY\x10\x01\"/\n" +
	"\bProtocol\x12\a\n" +
	"\x03TCP\x10\x00\x12\a\n" +
	"\x03UDP\x10\x01\x12\b\n" +
	"\x04ICMP\x10\x02\x12\a\n" +
	"\x03ANY\x10\x03\"J\n" +
	"\x18SetNetworkPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x12\n" +
	"\x10GetHealthRequest\"\x92\x01\n" +
	"\x11GetHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1d\n" +
	"\n" +
	"ovs_status\x18\x02 \x01(\tR\tovsStatus\x12\x1d\n" +
	"\n" +
	"ovn_status\x18\x03 \x01(\tR\tovnStatus\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x04R\ruptimeSeconds2\x83\x05\n" +
	"\x0eNetworkControl\x12U\n" +
	"\fCreateBridge\x12!.arca.network.CreateBridgeRequest\x1a\".arca.network.CreateBridgeResponse\x12U\n" +
	"\fDeleteBridge\x12!.arca.network.DeleteBridgeRequest\x1a\".arca.network.DeleteBridgeResponse\x12^\n" +
	"\x0fAttachContainer\x12$.arca.network.AttachContainerRequest\x1a%.arca.network.AttachContainerResponse\x12^\n" +
	"\x0fDetachContainer\x12$.arca.network.DetachContainerRequest\x1a%.arca.network.DetachContainerResponse\x12R\n" +
	"\vListBridges\x12 .arca.network.ListBridgesRequest\x1a!.arca.network.ListBridgesResponse\x12a\n" +
	"\x10SetNetworkPolicy\x12%.arca.network.SetNetworkPolicyRequest\x1a&.arca.network.SetNetworkPolicyResponse\x12L\n" +
	"\tGetHealth\x12\x1e.arca.network.GetHealthRequest\x1a\x1f.arca.network.GetHealthResponseB\x18Z\x16arca-network-api/protob\x06proto3"

var (
	file_network_proto_rawDescOnce sync.Once
	file_network_proto_rawDescData []byte
)

func file_network_proto_rawDescGZIP() []byte {
	file_network_proto_rawDescOnce.Do(func() {
		file_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)))
	})
	return file_network_proto_rawDescData
}

var file_network_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_network_proto_goTypes = []any{
	(NetworkPolicyRule_Action)(0),    // 0: arca.network.NetworkPolicyRule.Action
	(NetworkPolicyRule_Protocol)(0),  // 1: arca.network.NetworkPolicyRule.Protocol
	(*CreateBridgeRequest)(nil),      // 2: arca.network.CreateBridgeRequest
	(*CreateBridgeResponse)(nil),     // 3: arca.network.CreateBridgeResponse
	(*DeleteBridgeRequest)(nil),      // 4: arca.network.DeleteBridgeRequest
	(*DeleteBridgeResponse)(nil),     // 5: arca.network.DeleteBridgeResponse
	(*AttachContainerRequest)(nil),   // 6: arca.network.AttachContainerRequest
	(*AttachContainerResponse)(nil),  // 7: arca.network.AttachContainerResponse
	(*DetachContainerRequest)(nil),   // 8: arca.network.DetachContainerRequest
	(*DetachContainerResponse)(nil),  // 9: arca.network.DetachContainerResponse
	(*ListBridgesRequest)(nil),       // 10: arca.network.ListBridgesRequest
	(*BridgeInfo)(nil),               // 11: arca.network.BridgeInfo
	(*ListBridgesResponse)(nil),      // 12: arca.network.ListBridgesResponse
	(*SetNetworkPolicyRequest)(nil),  // 13: arca.network.SetNetworkPolicyRequest
	(*NetworkPolicyRule)(nil),        // 14: arca.network.NetworkPolicyRule
	(*SetNetworkPolicyResponse)(nil), // 15: arca.network.SetNetworkPolicyResponse
	(*GetHealthRequest)(nil),         // 16: arca.network.GetHealthRequest
	(*GetHealthResponse)(nil),        // 17: arca.network.GetHealthResponse
}
var file_network_proto_depIdxs = []int32{
	11, // 0: arca.network.ListBridgesResponse.bridges:type_name -> arca.network.BridgeInfo
	14, // 1: arca.network.SetNetworkPolicyRequest.rules:type_name -> arca.network.NetworkPolicyRule
	0,  // 2: arca.network.NetworkPolicyRule.action:type_name -> arca.network.NetworkPolicyRule.Action
	1,  // 3: arca.network.NetworkPolicyRule.protocol:type_name -> arca.network.NetworkPolicyRule.Protocol
	2,  // 4: arca.network.NetworkControl.CreateBridge:input_type -> arca.network.CreateBridgeRequest
	4,  // 5: arca.network.NetworkControl.DeleteBridge:input_type -> arca.network.DeleteBridgeRequest
	6,  // 6: arca.network.NetworkControl.AttachContainer:input_type -> arca.network.AttachContainerRequest
	8,  // 7: arca.network.NetworkControl.DetachContainer:input_type -> arca.network.DetachContainerRequest
	10, // 8: arca.network.NetworkControl.ListBridges:input_type -> arca.network.ListBridgesRequest
	13, // 9: arca.network.NetworkControl.SetNetworkPolicy:input_type -> arca.network.SetNetworkPolicyRequest
	16, // 10: arca.network.NetworkControl.GetHealth:input_type -> arca.network.GetHealthRequest
	3,  // 11: arca.network.NetworkControl.CreateBridge:output_type -> arca.network.CreateBridgeResponse
	5,  // 12: arca.network.NetworkControl.DeleteBridge:output_type -> arca.network.DeleteBridgeResponse
	7,  // 13: arca.network.NetworkControl.AttachContainer:output_type -> arca.network.AttachContainerResponse
	9,  // 14: arca.network.NetworkControl.DetachContainer:output_type -> arca.network.DetachContainerResponse
	12, // 15: arca.network.NetworkControl.ListBridges:output_type -> arca.network.ListBridgesResponse
	15, // 16: arca.network.NetworkControl.SetNetworkPolicy:output_type -> arca.network.SetNetworkPolicyResponse
	17, // 17: arca.network.NetworkControl.GetHealth:output_type -> arca.network.GetHealthResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		EnumInfos:         file_network_proto_enumTypes,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
