// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: network.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkControl_CreateBridge_FullMethodName         = "/arca.network.NetworkControl/CreateBridge"
	NetworkControl_DeleteBridge_FullMethodName         = "/arca.network.NetworkControl/DeleteBridge"
	NetworkControl_AttachContainer_FullMethodName      = "/arca.network.NetworkControl/AttachContainer"
	NetworkControl_DetachContainer_FullMethodName      = "/arca.network.NetworkControl/DetachContainer"
	NetworkControl_ListBridges_FullMethodName          = "/arca.network.NetworkControl/ListBridges"
	NetworkControl_SetNetworkPolicy_FullMethodName     = "/arca.network.NetworkControl/SetNetworkPolicy"
	NetworkControl_GetHealth_FullMethodName            = "/arca.network.NetworkControl/GetHealth"
	NetworkControl_ResolveDNS_FullMethodName           = "/arca.network.NetworkControl/ResolveDNS"
	NetworkControl_GetContainerNetworks_FullMethodName = "/arca.network.NetworkControl/GetContainerNetworks"
)

// NetworkControlClient is the client API for NetworkControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NetworkControl service provides OVN/OVS management operations
type NetworkControlClient interface {
	// CreateBridge creates a new OVS bridge and OVN logical switch
	CreateBridge(ctx context.Context, in *CreateBridgeRequest, opts ...grpc.CallOption) (*CreateBridgeResponse, error)
	// DeleteBridge removes an OVS bridge and OVN logical switch
	DeleteBridge(ctx context.Context, in *DeleteBridgeRequest, opts ...grpc.CallOption) (*DeleteBridgeResponse, error)
	// AttachContainer attaches a container to a network
	AttachContainer(ctx context.Context, in *AttachContainerRequest, opts ...grpc.CallOption) (*AttachContainerResponse, error)
	// DetachContainer detaches a container from a network
	DetachContainer(ctx context.Context, in *DetachContainerRequest, opts ...grpc.CallOption) (*DetachContainerResponse, error)
	// ListBridges returns all bridges
	ListBridges(ctx context.Context, in *ListBridgesRequest, opts ...grpc.CallOption) (*ListBridgesResponse, error)
	// SetNetworkPolicy sets network policies for a network
	SetNetworkPolicy(ctx context.Context, in *SetNetworkPolicyRequest, opts ...grpc.CallOption) (*SetNetworkPolicyResponse, error)
	// GetHealth returns health status of the helper VM
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
	// ResolveDNS resolves a hostname across multiple networks (for embedded DNS in vminit)
	ResolveDNS(ctx context.Context, in *ResolveDNSRequest, opts ...grpc.CallOption) (*ResolveDNSResponse, error)
	// GetContainerNetworks returns the list of networks a container is attached to
	GetContainerNetworks(ctx context.Context, in *GetContainerNetworksRequest, opts ...grpc.CallOption) (*GetContainerNetworksResponse, error)
}

type networkControlClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkControlClient(cc grpc.ClientConnInterface) NetworkControlClient {
	return &networkControlClient{cc}
}

func (c *networkControlClient) CreateBridge(ctx context.Context, in *CreateBridgeRequest, opts ...grpc.CallOption) (*CreateBridgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBridgeResponse)
	err := c.cc.Invoke(ctx, NetworkControl_CreateBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControlClient) DeleteBridge(ctx context.Context, in *DeleteBridgeRequest, opts ...grpc.CallOption) (*DeleteBridgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBridgeResponse)
	err := c.cc.Invoke(ctx, NetworkControl_DeleteBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControlClient) AttachContainer(ctx context.Context, in *AttachContainerRequest, opts ...grpc.CallOption) (*AttachContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachContainerResponse)
	err := c.cc.Invoke(ctx, NetworkControl_AttachContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControlClient) DetachContainer(ctx context.Context, in *DetachContainerRequest, opts ...grpc.CallOption) (*DetachContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachContainerResponse)
	err := c.cc.Invoke(ctx, NetworkControl_DetachContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControlClient) ListBridges(ctx context.Context, in *ListBridgesRequest, opts ...grpc.CallOption) (*ListBridgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBridgesResponse)
	err := c.cc.Invoke(ctx, NetworkControl_ListBridges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControlClient) SetNetworkPolicy(ctx context.Context, in *SetNetworkPolicyRequest, opts ...grpc.CallOption) (*SetNetworkPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNetworkPolicyResponse)
	err := c.cc.Invoke(ctx, NetworkControl_SetNetworkPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControlClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, NetworkControl_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControlClient) ResolveDNS(ctx context.Context, in *ResolveDNSRequest, opts ...grpc.CallOption) (*ResolveDNSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveDNSResponse)
	err := c.cc.Invoke(ctx, NetworkControl_ResolveDNS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControlClient) GetContainerNetworks(ctx context.Context, in *GetContainerNetworksRequest, opts ...grpc.CallOption) (*GetContainerNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainerNetworksResponse)
	err := c.cc.Invoke(ctx, NetworkControl_GetContainerNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkControlServer is the server API for NetworkControl service.
// All implementations must embed UnimplementedNetworkControlServer
// for forward compatibility.
//
// NetworkControl service provides OVN/OVS management operations
type NetworkControlServer interface {
	// CreateBridge creates a new OVS bridge and OVN logical switch
	CreateBridge(context.Context, *CreateBridgeRequest) (*CreateBridgeResponse, error)
	// DeleteBridge removes an OVS bridge and OVN logical switch
	DeleteBridge(context.Context, *DeleteBridgeRequest) (*DeleteBridgeResponse, error)
	// AttachContainer attaches a container to a network
	AttachContainer(context.Context, *AttachContainerRequest) (*AttachContainerResponse, error)
	// DetachContainer detaches a container from a network
	DetachContainer(context.Context, *DetachContainerRequest) (*DetachContainerResponse, error)
	// ListBridges returns all bridges
	ListBridges(context.Context, *ListBridgesRequest) (*ListBridgesResponse, error)
	// SetNetworkPolicy sets network policies for a network
	SetNetworkPolicy(context.Context, *SetNetworkPolicyRequest) (*SetNetworkPolicyResponse, error)
	// GetHealth returns health status of the helper VM
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	// ResolveDNS resolves a hostname across multiple networks (for embedded DNS in vminit)
	ResolveDNS(context.Context, *ResolveDNSRequest) (*ResolveDNSResponse, error)
	// GetContainerNetworks returns the list of networks a container is attached to
	GetContainerNetworks(context.Context, *GetContainerNetworksRequest) (*GetContainerNetworksResponse, error)
	mustEmbedUnimplementedNetworkControlServer()
}

// UnimplementedNetworkControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkControlServer struct{}

func (UnimplementedNetworkControlServer) CreateBridge(context.Context, *CreateBridgeRequest) (*CreateBridgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBridge not implemented")
}
func (UnimplementedNetworkControlServer) DeleteBridge(context.Context, *DeleteBridgeRequest) (*DeleteBridgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBridge not implemented")
}
func (UnimplementedNetworkControlServer) AttachContainer(context.Context, *AttachContainerRequest) (*AttachContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachContainer not implemented")
}
func (UnimplementedNetworkControlServer) DetachContainer(context.Context, *DetachContainerRequest) (*DetachContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetachContainer not implemented")
}
func (UnimplementedNetworkControlServer) ListBridges(context.Context, *ListBridgesRequest) (*ListBridgesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBridges not implemented")
}
func (UnimplementedNetworkControlServer) SetNetworkPolicy(context.Context, *SetNetworkPolicyRequest) (*SetNetworkPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNetworkPolicy not implemented")
}
func (UnimplementedNetworkControlServer) GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedNetworkControlServer) ResolveDNS(context.Context, *ResolveDNSRequest) (*ResolveDNSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveDNS not implemented")
}
func (UnimplementedNetworkControlServer) GetContainerNetworks(context.Context, *GetContainerNetworksRequest) (*GetContainerNetworksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContainerNetworks not implemented")
}
func (UnimplementedNetworkControlServer) mustEmbedUnimplementedNetworkControlServer() {}
func (UnimplementedNetworkControlServer) testEmbeddedByValue()                        {}

// UnsafeNetworkControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkControlServer will
// result in compilation errors.
type UnsafeNetworkControlServer interface {
	mustEmbedUnimplementedNetworkControlServer()
}

func RegisterNetworkControlServer(s grpc.ServiceRegistrar, srv NetworkControlServer) {
	// If the following call pancis, it indicates UnimplementedNetworkControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkControl_ServiceDesc, srv)
}

func _NetworkControl_CreateBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControlServer).CreateBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkControl_CreateBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControlServer).CreateBridge(ctx, req.(*CreateBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkControl_DeleteBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControlServer).DeleteBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkControl_DeleteBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControlServer).DeleteBridge(ctx, req.(*DeleteBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkControl_AttachContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControlServer).AttachContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkControl_AttachContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControlServer).AttachContainer(ctx, req.(*AttachContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkControl_DetachContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControlServer).DetachContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkControl_DetachContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControlServer).DetachContainer(ctx, req.(*DetachContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkControl_ListBridges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBridgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControlServer).ListBridges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkControl_ListBridges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControlServer).ListBridges(ctx, req.(*ListBridgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkControl_SetNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNetworkPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControlServer).SetNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkControl_SetNetworkPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControlServer).SetNetworkPolicy(ctx, req.(*SetNetworkPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkControl_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControlServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkControl_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControlServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkControl_ResolveDNS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveDNSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControlServer).ResolveDNS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkControl_ResolveDNS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControlServer).ResolveDNS(ctx, req.(*ResolveDNSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkControl_GetContainerNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControlServer).GetContainerNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkControl_GetContainerNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControlServer).GetContainerNetworks(ctx, req.(*GetContainerNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkControl_ServiceDesc is the grpc.ServiceDesc for NetworkControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arca.network.NetworkControl",
	HandlerType: (*NetworkControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBridge",
			Handler:    _NetworkControl_CreateBridge_Handler,
		},
		{
			MethodName: "DeleteBridge",
			Handler:    _NetworkControl_DeleteBridge_Handler,
		},
		{
			MethodName: "AttachContainer",
			Handler:    _NetworkControl_AttachContainer_Handler,
		},
		{
			MethodName: "DetachContainer",
			Handler:    _NetworkControl_DetachContainer_Handler,
		},
		{
			MethodName: "ListBridges",
			Handler:    _NetworkControl_ListBridges_Handler,
		},
		{
			MethodName: "SetNetworkPolicy",
			Handler:    _NetworkControl_SetNetworkPolicy_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _NetworkControl_GetHealth_Handler,
		},
		{
			MethodName: "ResolveDNS",
			Handler:    _NetworkControl_ResolveDNS_Handler,
		},
		{
			MethodName: "GetContainerNetworks",
			Handler:    _NetworkControl_GetContainerNetworks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network.proto",
}
