// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: router.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVLANRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VLAN ID (100-4094)
	VlanId uint32 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	// Network subnet in CIDR notation (e.g., "172.18.0.0/16")
	Subnet string `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	// Gateway IP address (e.g., "172.18.0.1")
	// This IP will be assigned to the VLAN interface
	Gateway string `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Network name (for DNS/logging)
	NetworkName string `protobuf:"bytes,4,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	// Optional: MTU for the VLAN interface
	Mtu uint32 `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Optional: Enable NAT for this network (default: true)
	EnableNat     bool `protobuf:"varint,6,opt,name=enable_nat,json=enableNat,proto3" json:"enable_nat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVLANRequest) Reset() {
	*x = CreateVLANRequest{}
	mi := &file_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVLANRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVLANRequest) ProtoMessage() {}

func (x *CreateVLANRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVLANRequest.ProtoReflect.Descriptor instead.
func (*CreateVLANRequest) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVLANRequest) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *CreateVLANRequest) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *CreateVLANRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *CreateVLANRequest) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *CreateVLANRequest) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *CreateVLANRequest) GetEnableNat() bool {
	if x != nil {
		return x.EnableNat
	}
	return false
}

type CreateVLANResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Created interface name (e.g., "eth0.100")
	InterfaceName string `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// Gateway MAC address
	MacAddress string `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVLANResponse) Reset() {
	*x = CreateVLANResponse{}
	mi := &file_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVLANResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVLANResponse) ProtoMessage() {}

func (x *CreateVLANResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVLANResponse.ProtoReflect.Descriptor instead.
func (*CreateVLANResponse) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVLANResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateVLANResponse) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *CreateVLANResponse) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *CreateVLANResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteVLANRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VLAN ID to delete
	VlanId        uint32 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVLANRequest) Reset() {
	*x = DeleteVLANRequest{}
	mi := &file_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVLANRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVLANRequest) ProtoMessage() {}

func (x *DeleteVLANRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVLANRequest.ProtoReflect.Descriptor instead.
func (*DeleteVLANRequest) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteVLANRequest) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

type DeleteVLANResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVLANResponse) Reset() {
	*x = DeleteVLANResponse{}
	mi := &file_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVLANResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVLANResponse) ProtoMessage() {}

func (x *DeleteVLANResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVLANResponse.ProtoReflect.Descriptor instead.
func (*DeleteVLANResponse) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteVLANResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteVLANResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfigureNATRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VLAN ID
	VlanId uint32 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	// Source subnet to NAT (e.g., "172.18.0.0/16")
	SourceSubnet  string `protobuf:"bytes,2,opt,name=source_subnet,json=sourceSubnet,proto3" json:"source_subnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureNATRequest) Reset() {
	*x = ConfigureNATRequest{}
	mi := &file_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureNATRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureNATRequest) ProtoMessage() {}

func (x *ConfigureNATRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureNATRequest.ProtoReflect.Descriptor instead.
func (*ConfigureNATRequest) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureNATRequest) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *ConfigureNATRequest) GetSourceSubnet() string {
	if x != nil {
		return x.SourceSubnet
	}
	return ""
}

type ConfigureNATResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureNATResponse) Reset() {
	*x = ConfigureNATResponse{}
	mi := &file_router_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureNATResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureNATResponse) ProtoMessage() {}

func (x *ConfigureNATResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureNATResponse.ProtoReflect.Descriptor instead.
func (*ConfigureNATResponse) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigureNATResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureNATResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RemoveNATRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VLAN ID
	VlanId uint32 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	// Source subnet that was NATed
	SourceSubnet  string `protobuf:"bytes,2,opt,name=source_subnet,json=sourceSubnet,proto3" json:"source_subnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNATRequest) Reset() {
	*x = RemoveNATRequest{}
	mi := &file_router_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNATRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNATRequest) ProtoMessage() {}

func (x *RemoveNATRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNATRequest.ProtoReflect.Descriptor instead.
func (*RemoveNATRequest) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveNATRequest) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *RemoveNATRequest) GetSourceSubnet() string {
	if x != nil {
		return x.SourceSubnet
	}
	return ""
}

type RemoveNATResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNATResponse) Reset() {
	*x = RemoveNATResponse{}
	mi := &file_router_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNATResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNATResponse) ProtoMessage() {}

func (x *RemoveNATResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNATResponse.ProtoReflect.Descriptor instead.
func (*RemoveNATResponse) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveNATResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveNATResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfigureDNSRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VLAN ID
	VlanId uint32 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	// Network subnet (e.g., "172.18.0.0/16")
	Subnet string `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	// Gateway IP (DNS server will listen here)
	Gateway string `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// DNS domain for container name resolution
	// e.g., "frontend.docker.internal"
	Domain string `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	// Container hostname → IP mappings
	Hosts         map[string]string `protobuf:"bytes,5,rep,name=hosts,proto3" json:"hosts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureDNSRequest) Reset() {
	*x = ConfigureDNSRequest{}
	mi := &file_router_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureDNSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureDNSRequest) ProtoMessage() {}

func (x *ConfigureDNSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureDNSRequest.ProtoReflect.Descriptor instead.
func (*ConfigureDNSRequest) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigureDNSRequest) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *ConfigureDNSRequest) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *ConfigureDNSRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *ConfigureDNSRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ConfigureDNSRequest) GetHosts() map[string]string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type ConfigureDNSResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureDNSResponse) Reset() {
	*x = ConfigureDNSResponse{}
	mi := &file_router_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureDNSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureDNSResponse) ProtoMessage() {}

func (x *ConfigureDNSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureDNSResponse.ProtoReflect.Descriptor instead.
func (*ConfigureDNSResponse) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigureDNSResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureDNSResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddPortMappingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container IP address
	ContainerIp string `protobuf:"bytes,1,opt,name=container_ip,json=containerIp,proto3" json:"container_ip,omitempty"`
	// Container port
	ContainerPort uint32 `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	// Host port to expose
	HostPort uint32 `protobuf:"varint,3,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	// Protocol (tcp/udp)
	Protocol string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// VLAN ID (for routing back to container)
	VlanId        uint32 `protobuf:"varint,5,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPortMappingRequest) Reset() {
	*x = AddPortMappingRequest{}
	mi := &file_router_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPortMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPortMappingRequest) ProtoMessage() {}

func (x *AddPortMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPortMappingRequest.ProtoReflect.Descriptor instead.
func (*AddPortMappingRequest) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{10}
}

func (x *AddPortMappingRequest) GetContainerIp() string {
	if x != nil {
		return x.ContainerIp
	}
	return ""
}

func (x *AddPortMappingRequest) GetContainerPort() uint32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *AddPortMappingRequest) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *AddPortMappingRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AddPortMappingRequest) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

type AddPortMappingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPortMappingResponse) Reset() {
	*x = AddPortMappingResponse{}
	mi := &file_router_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPortMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPortMappingResponse) ProtoMessage() {}

func (x *AddPortMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPortMappingResponse.ProtoReflect.Descriptor instead.
func (*AddPortMappingResponse) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{11}
}

func (x *AddPortMappingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddPortMappingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RemovePortMappingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host port to remove
	HostPort uint32 `protobuf:"varint,1,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	// Protocol (tcp/udp)
	Protocol      string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePortMappingRequest) Reset() {
	*x = RemovePortMappingRequest{}
	mi := &file_router_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePortMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePortMappingRequest) ProtoMessage() {}

func (x *RemovePortMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePortMappingRequest.ProtoReflect.Descriptor instead.
func (*RemovePortMappingRequest) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{12}
}

func (x *RemovePortMappingRequest) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *RemovePortMappingRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type RemovePortMappingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePortMappingResponse) Reset() {
	*x = RemovePortMappingResponse{}
	mi := &file_router_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePortMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePortMappingResponse) ProtoMessage() {}

func (x *RemovePortMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePortMappingResponse.ProtoReflect.Descriptor instead.
func (*RemovePortMappingResponse) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{13}
}

func (x *RemovePortMappingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemovePortMappingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListVLANsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: Filter by VLAN ID
	VlanId        uint32 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVLANsRequest) Reset() {
	*x = ListVLANsRequest{}
	mi := &file_router_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVLANsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVLANsRequest) ProtoMessage() {}

func (x *ListVLANsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVLANsRequest.ProtoReflect.Descriptor instead.
func (*ListVLANsRequest) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{14}
}

func (x *ListVLANsRequest) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

type ListVLANsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of VLAN interfaces
	Vlans []*VLANInterface `protobuf:"bytes,1,rep,name=vlans,proto3" json:"vlans,omitempty"`
	// Error message if retrieval failed
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVLANsResponse) Reset() {
	*x = ListVLANsResponse{}
	mi := &file_router_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVLANsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVLANsResponse) ProtoMessage() {}

func (x *ListVLANsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVLANsResponse.ProtoReflect.Descriptor instead.
func (*ListVLANsResponse) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{15}
}

func (x *ListVLANsResponse) GetVlans() []*VLANInterface {
	if x != nil {
		return x.Vlans
	}
	return nil
}

func (x *ListVLANsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VLANInterface struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VLAN ID
	VlanId uint32 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	// Interface name (e.g., "eth0.100")
	InterfaceName string `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// Gateway IP address
	Gateway string `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Subnet in CIDR notation
	Subnet string `protobuf:"bytes,4,opt,name=subnet,proto3" json:"subnet,omitempty"`
	// MAC address
	MacAddress string `protobuf:"bytes,5,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// MTU
	Mtu uint32 `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Interface is up
	IsUp bool `protobuf:"varint,7,opt,name=is_up,json=isUp,proto3" json:"is_up,omitempty"`
	// NAT enabled
	NatEnabled    bool `protobuf:"varint,8,opt,name=nat_enabled,json=natEnabled,proto3" json:"nat_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VLANInterface) Reset() {
	*x = VLANInterface{}
	mi := &file_router_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VLANInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VLANInterface) ProtoMessage() {}

func (x *VLANInterface) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VLANInterface.ProtoReflect.Descriptor instead.
func (*VLANInterface) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{16}
}

func (x *VLANInterface) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *VLANInterface) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *VLANInterface) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *VLANInterface) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *VLANInterface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *VLANInterface) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *VLANInterface) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

func (x *VLANInterface) GetNatEnabled() bool {
	if x != nil {
		return x.NatEnabled
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_router_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{17}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service is healthy
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Status message
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Number of active VLANs
	ActiveVlans uint32 `protobuf:"varint,3,opt,name=active_vlans,json=activeVlans,proto3" json:"active_vlans,omitempty"`
	// Service uptime in seconds
	UptimeSeconds uint64 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_router_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{18}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetActiveVlans() uint32 {
	if x != nil {
		return x.ActiveVlans
	}
	return 0
}

func (x *HealthResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_router_proto protoreflect.FileDescriptor

const file_router_proto_rawDesc = "" +
	"\n" +
	"\frouter.proto\x12\x06router\"\xb2\x01\n" +
	"\x11CreateVLANRequest\x12\x17\n" +
	"\avlan_id\x18\x01 \x01(\rR\x06vlanId\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\tR\x06subnet\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway\x12!\n" +
	"\fnetwork_name\x18\x04 \x01(\tR\vnetworkName\x12\x10\n" +
	"\x03mtu\x18\x05 \x01(\rR\x03mtu\x12\x1d\n" +
	"\n" +
	"enable_nat\x18\x06 \x01(\bR\tenableNat\"\x8c\x01\n" +
	"\x12CreateVLANResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\",\n" +
	"\x11DeleteVLANRequest\x12\x17\n" +
	"\avlan_id\x18\x01 \x01(\rR\x06vlanId\"D\n" +
	"\x12DeleteVLANResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"S\n" +
	"\x13ConfigureNATRequest\x12\x17\n" +
	"\avlan_id\x18\x01 \x01(\rR\x06vlanId\x12#\n" +
	"\rsource_subnet\x18\x02 \x01(\tR\fsourceSubnet\"F\n" +
	"\x14ConfigureNATResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"P\n" +
	"\x10RemoveNATRequest\x12\x17\n" +
	"\avlan_id\x18\x01 \x01(\rR\x06vlanId\x12#\n" +
	"\rsource_subnet\x18\x02 \x01(\tR\fsourceSubnet\"C\n" +
	"\x11RemoveNATResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xf0\x01\n" +
	"\x13ConfigureDNSRequest\x12\x17\n" +
	"\avlan_id\x18\x01 \x01(\rR\x06vlanId\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\tR\x06subnet\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12<\n" +
	"\x05hosts\x18\x05 \x03(\v2&.router.ConfigureDNSRequest.HostsEntryR\x05hosts\x1a8\n" +
	"\n" +
	"HostsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x14ConfigureDNSResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb3\x01\n" +
	"\x15AddPortMappingRequest\x12!\n" +
	"\fcontainer_ip\x18\x01 \x01(\tR\vcontainerIp\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\rR\rcontainerPort\x12\x1b\n" +
	"\thost_port\x18\x03 \x01(\rR\bhostPort\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x17\n" +
	"\avlan_id\x18\x05 \x01(\rR\x06vlanId\"H\n" +
	"\x16AddPortMappingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"S\n" +
	"\x18RemovePortMappingRequest\x12\x1b\n" +
	"\thost_port\x18\x01 \x01(\rR\bhostPort\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\"K\n" +
	"\x19RemovePortMappingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\x10ListVLANsRequest\x12\x17\n" +
	"\avlan_id\x18\x01 \x01(\rR\x06vlanId\"V\n" +
	"\x11ListVLANsResponse\x12+\n" +
	"\x05vlans\x18\x01 \x03(\v2\x15.router.VLANInterfaceR\x05vlans\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xea\x01\n" +
	"\rVLANInterface\x12\x17\n" +
	"\avlan_id\x18\x01 \x01(\rR\x06vlanId\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway\x12\x16\n" +
	"\x06subnet\x18\x04 \x01(\tR\x06subnet\x12\x1f\n" +
	"\vmac_address\x18\x05 \x01(\tR\n" +
	"macAddress\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\rR\x03mtu\x12\x13\n" +
	"\x05is_up\x18\a \x01(\bR\x04isUp\x12\x1f\n" +
	"\vnat_enabled\x18\b \x01(\bR\n" +
	"natEnabled\"\x0f\n" +
	"\rHealthRequest\"\x8c\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\factive_vlans\x18\x03 \x01(\rR\vactiveVlans\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x04R\ruptimeSeconds2\x9a\x05\n" +
	"\rRouterService\x12C\n" +
	"\n" +
	"CreateVLAN\x12\x19.router.CreateVLANRequest\x1a\x1a.router.CreateVLANResponse\x12C\n" +
	"\n" +
	"DeleteVLAN\x12\x19.router.DeleteVLANRequest\x1a\x1a.router.DeleteVLANResponse\x12I\n" +
	"\fConfigureNAT\x12\x1b.router.ConfigureNATRequest\x1a\x1c.router.ConfigureNATResponse\x12@\n" +
	"\tRemoveNAT\x12\x18.router.RemoveNATRequest\x1a\x19.router.RemoveNATResponse\x12I\n" +
	"\fConfigureDNS\x12\x1b.router.ConfigureDNSRequest\x1a\x1c.router.ConfigureDNSResponse\x12O\n" +
	"\x0eAddPortMapping\x12\x1d.router.AddPortMappingRequest\x1a\x1e.router.AddPortMappingResponse\x12X\n" +
	"\x11RemovePortMapping\x12 .router.RemovePortMappingRequest\x1a!.router.RemovePortMappingResponse\x12@\n" +
	"\tListVLANs\x12\x18.router.ListVLANsRequest\x1a\x19.router.ListVLANsResponse\x12:\n" +
	"\tGetHealth\x12\x15.router.HealthRequest\x1a\x16.router.HealthResponseBFZDgithub.com/Liquescent-Development/arca/helpervm/router-service/protob\x06proto3"

var (
	file_router_proto_rawDescOnce sync.Once
	file_router_proto_rawDescData []byte
)

func file_router_proto_rawDescGZIP() []byte {
	file_router_proto_rawDescOnce.Do(func() {
		file_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_proto_rawDesc), len(file_router_proto_rawDesc)))
	})
	return file_router_proto_rawDescData
}

var file_router_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_router_proto_goTypes = []any{
	(*CreateVLANRequest)(nil),         // 0: router.CreateVLANRequest
	(*CreateVLANResponse)(nil),        // 1: router.CreateVLANResponse
	(*DeleteVLANRequest)(nil),         // 2: router.DeleteVLANRequest
	(*DeleteVLANResponse)(nil),        // 3: router.DeleteVLANResponse
	(*ConfigureNATRequest)(nil),       // 4: router.ConfigureNATRequest
	(*ConfigureNATResponse)(nil),      // 5: router.ConfigureNATResponse
	(*RemoveNATRequest)(nil),          // 6: router.RemoveNATRequest
	(*RemoveNATResponse)(nil),         // 7: router.RemoveNATResponse
	(*ConfigureDNSRequest)(nil),       // 8: router.ConfigureDNSRequest
	(*ConfigureDNSResponse)(nil),      // 9: router.ConfigureDNSResponse
	(*AddPortMappingRequest)(nil),     // 10: router.AddPortMappingRequest
	(*AddPortMappingResponse)(nil),    // 11: router.AddPortMappingResponse
	(*RemovePortMappingRequest)(nil),  // 12: router.RemovePortMappingRequest
	(*RemovePortMappingResponse)(nil), // 13: router.RemovePortMappingResponse
	(*ListVLANsRequest)(nil),          // 14: router.ListVLANsRequest
	(*ListVLANsResponse)(nil),         // 15: router.ListVLANsResponse
	(*VLANInterface)(nil),             // 16: router.VLANInterface
	(*HealthRequest)(nil),             // 17: router.HealthRequest
	(*HealthResponse)(nil),            // 18: router.HealthResponse
	nil,                               // 19: router.ConfigureDNSRequest.HostsEntry
}
var file_router_proto_depIdxs = []int32{
	19, // 0: router.ConfigureDNSRequest.hosts:type_name -> router.ConfigureDNSRequest.HostsEntry
	16, // 1: router.ListVLANsResponse.vlans:type_name -> router.VLANInterface
	0,  // 2: router.RouterService.CreateVLAN:input_type -> router.CreateVLANRequest
	2,  // 3: router.RouterService.DeleteVLAN:input_type -> router.DeleteVLANRequest
	4,  // 4: router.RouterService.ConfigureNAT:input_type -> router.ConfigureNATRequest
	6,  // 5: router.RouterService.RemoveNAT:input_type -> router.RemoveNATRequest
	8,  // 6: router.RouterService.ConfigureDNS:input_type -> router.ConfigureDNSRequest
	10, // 7: router.RouterService.AddPortMapping:input_type -> router.AddPortMappingRequest
	12, // 8: router.RouterService.RemovePortMapping:input_type -> router.RemovePortMappingRequest
	14, // 9: router.RouterService.ListVLANs:input_type -> router.ListVLANsRequest
	17, // 10: router.RouterService.GetHealth:input_type -> router.HealthRequest
	1,  // 11: router.RouterService.CreateVLAN:output_type -> router.CreateVLANResponse
	3,  // 12: router.RouterService.DeleteVLAN:output_type -> router.DeleteVLANResponse
	5,  // 13: router.RouterService.ConfigureNAT:output_type -> router.ConfigureNATResponse
	7,  // 14: router.RouterService.RemoveNAT:output_type -> router.RemoveNATResponse
	9,  // 15: router.RouterService.ConfigureDNS:output_type -> router.ConfigureDNSResponse
	11, // 16: router.RouterService.AddPortMapping:output_type -> router.AddPortMappingResponse
	13, // 17: router.RouterService.RemovePortMapping:output_type -> router.RemovePortMappingResponse
	15, // 18: router.RouterService.ListVLANs:output_type -> router.ListVLANsResponse
	18, // 19: router.RouterService.GetHealth:output_type -> router.HealthResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_router_proto_init() }
func file_router_proto_init() {
	if File_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_proto_rawDesc), len(file_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_router_proto_goTypes,
		DependencyIndexes: file_router_proto_depIdxs,
		MessageInfos:      file_router_proto_msgTypes,
	}.Build()
	File_router_proto = out.File
	file_router_proto_goTypes = nil
	file_router_proto_depIdxs = nil
}
