// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by Makefile during build
// To regenerate: make gen-buildinfo

import Foundation

/// Build-time information injected by Makefile
public struct ArcaBuildInfo {
    /// Git commit hash at build time
    public static let gitCommit = "3f4dfd5"

    /// ISO8601 timestamp of build
    public static let buildTime = "2025-12-01T19:45:32Z"
}
